### PR TITLE
WWWelcome to the neWWW WhatTheFest

### LINKED ISSUE #64: Clean up and simplify design
Working on a 2017 update with @lukaszklis: https://github.com/lukaszklis/wwwtf.berlin

- [ ] Remove the two lines ("We welcome…") below "A full week of…"
- [ ] Main nav: Add github, use octocat icon instead of text
- [ ] Main nav: use twitter icon instead of text
- [ ] simplify logo
- [ ] remove dropdown effect from list items (we can scroll, better to see everything at once)
- [ ] user some prettier colors :)

some quick work-in-progress ideas:

wwwtf-tablet-hover
wwwtf-tablet
wwwtf mobile

### PR DESCRIPTION
**Pull request by lukaszklis**
Fixes #64, pairing with @Kriesse.

”Live Preview”: http://wwwtf.dev.klis.co/

### CODE REVIEW

**Comment by Kriesse** [comment]
😍  Tested locally, LGTM

**Comment by janl** [comment]
This is lovely! The only thing I’m concerned is that it isn’t very clear that you need to scroll to get to the events. Is there any way we can maybe tease the event list by cutting it off at 100 or so pixels?

**Comment by Kriesse** [comment]
@janl Yup good point! Let's improve that. We have a little scroll indicator (think little subtly animated arrow) at the bottom, @lukaszklis I'll get you a mockup for this.

**Comment by Kriesse** [comment]
ping @janl – can we merge? 

The scroll issues has been addressed by adding a bouncy arrow and a link "Events" that takes you to the list. Preview:
http://wwwtf.dev.klis.co/

**Comment by janl** [comment]
I was more thinking something like this, smaller white margin of course, but that way the content is the signal to scroll, not an extra indicator, those always feel like “explaining the UI” instead of doing a good UI ;)

screen shot 2017-04-07 at 22 25 29

**Comment by janl** [comment]
but let’s get this merged, we can tweak later, thanks for all the hard wok!

**Comment by Kriesse** [comment]
<3

**Pull request merged**
