### PR TITLE
update page for 2018

### PR DESCRIPTION
**Pull request by ghost**
it's time!

this removes all past posts, but i'm sure that using some jekyll magic, we can keep them while not showing them on the main page (if that is desired)

### CODE REVIEW

**Comment by afknapping** [comment]
>  using some jekyll magic, we can keep them while not showing them on the main page

that'll only work if you don't delete them :)

here is how i would approach it:

- clone the index to a "2017"
- on the index, render only posts from 2018
- accordingly on "2017"

**Comment by ghost** [comment]
@filtercake yeah, that's what i was thinking

**Review by Kriesse — APPROVED** [review]
Yay! Thanks for kicking things off! LGTM

**Comment by afknapping** [comment]
> yeah, that's what i was thinking

ah, sorry, i thought you wanted to change this PR until the archive is ready... but can be a different one of course :)

**Comment by ghost** [comment]
@filtercake the question is whether we want to keep the old events in here at all? @Kriesse @janl

**Comment by Kriesse** [comment]
It'd be fine with me to just start fresh, and not having to build and maintain an archive first. That's what we did so far. 

If anyone wants to work on that though, go for it! Definitely would be nice to keep an archive. But it shouldn't stop moving forward with the 2018 site.

**Comment by afknapping** [comment]
(wrote some code to test the splitting by year but bundler is failing... will have a look another time...)

**Comment by afknapping** [comment]
just in case i never get around to it, here's what i've tried and worked:

```
{% for post in site.posts reversed %}
    {% capture year %}{{post.date | date: "%Y"}}{% endcapture %}
    {% if year == "2017" %}
        (event markup)
    {% endif %}
{% endfor %}
```
this way the 2017 files can stay in without building the archive yet which would spare to re-checkout them at a later point.

also, for a full archive it would make sense to copy over the css/sass too.

and yes, i'm aware that this is heavy bikeshedding in relation to get 2018 started – i just really like keeping things archived, apologies for hi-jacking the thread...

**Comment by ghost** [comment]
@filtercake that was exactly the solution i had in mind!

**Comment by ghost** [comment]
are we landing this in time for 2018 or can we land it now? @Kriesse @janl

**Comment by Kriesse** [comment]
@pup Is anything still blocking? I'm fine with merging this now (feel free to do it if you agree!). Also fine with me to start Twitter outreach to the community and encourage people to add their own events asap.

**Comment by ghost** [comment]
@Kriesse nope, no blockers as far as i know. i don't have access to the twitter account (and also don't have the rights to merge), but feel free to merge and announce it on twitter!

**Comment by Kriesse** [comment]
@pup and done! http://wwwtf.berlin/

**Comment by ghost** [comment]
https://twitter.com/wwwtfberlin/status/944236808166141952

**Pull request merged**
